/**
 * Extra lowercase search terms (countries, capitals, regions) keyed by exact IANA id.
 * Merged with path segments and Americas heuristics in getRegionalSearchTerms().
 */
const IANA_COUNTRY_CAPITAL = {
  "Africa/Abidjan": "ivory coast côte cote d'ivoire cote divoire abidjan",
  "Africa/Accra": "ghana accra",
  "Africa/Addis_Ababa": "ethiopia addis ababa",
  "Africa/Algiers": "algeria algiers",
  "Africa/Asmara": "eritrea asmara",
  "Africa/Bamako": "mali bamako",
  "Africa/Bangui": "central african republic bangui",
  "Africa/Banjul": "gambia banjul",
  "Africa/Bissau": "guinea-bissau bissau",
  "Africa/Blantyre": "malawi blantyre",
  "Africa/Brazzaville": "congo brazzaville republic of the congo",
  "Africa/Bujumbura": "burundi bujumbura",
  "Africa/Cairo": "egypt cairo",
  "Africa/Casablanca": "morocco casablanca",
  "Africa/Ceuta": "spain ceuta melilla",
  "Africa/Conakry": "guinea conakry",
  "Africa/Dakar": "senegal dakar",
  "Africa/Dar_es_Salaam": "tanzania dar es salaam",
  "Africa/Djibouti": "djibouti",
  "Africa/Douala": "cameroon douala",
  "Africa/El_Aaiun": "western sahara morocco el aaiun",
  "Africa/Freetown": "sierra leone freetown",
  "Africa/Gaborone": "botswana gaborone",
  "Africa/Harare": "zimbabwe harare",
  "Africa/Johannesburg": "south africa johannesburg cape pretoria",
  "Africa/Juba": "south sudan juba",
  "Africa/Kampala": "uganda kampala",
  "Africa/Khartoum": "sudan khartoum",
  "Africa/Kigali": "rwanda kigali",
  "Africa/Kinshasa": "democratic republic of the congo drc kinshasa",
  "Africa/Lagos": "nigeria lagos abuja",
  "Africa/Libreville": "gabon libreville",
  "Africa/Lome": "togo lome",
  "Africa/Luanda": "angola luanda",
  "Africa/Lubumbashi": "congo drc lubumbashi",
  "Africa/Lusaka": "zambia lusaka",
  "Africa/Malabo": "equatorial guinea malabo",
  "Africa/Maputo": "mozambique maputo",
  "Africa/Maseru": "lesotho maseru",
  "Africa/Mbabane": "eswatini swaziland mbabane",
  "Africa/Mogadishu": "somalia mogadishu",
  "Africa/Monrovia": "liberia monrovia",
  "Africa/Nairobi": "kenya nairobi",
  "Africa/Ndjamena": "chad ndjamena",
  "Africa/Niamey": "niger niamey",
  "Africa/Nouakchott": "mauritania nouakchott",
  "Africa/Ouagadougou": "burkina faso ouagadougou",
  "Africa/Porto-Novo": "benin porto novo cotonou",
  "Africa/Sao_Tome": "sao tome principe",
  "Africa/Tripoli": "libya tripoli",
  "Africa/Tunis": "tunisia tunis",
  "Africa/Windhoek": "namibia windhoek",
  "America/Adak": "usa united states alaska aleutian",
  "America/Anchorage": "usa united states alaska anchorage",
  "America/Anguilla": "anguilla",
  "America/Antigua": "antigua barbuda",
  "America/Araguaina": "brazil brasil araguaina",
  "America/Argentina/Buenos_Aires": "argentina buenos aires",
  "America/Argentina/Catamarca": "argentina catamarca",
  "America/Argentina/Cordoba": "argentina cordoba",
  "America/Argentina/Jujuy": "argentina jujuy",
  "America/Argentina/La_Rioja": "argentina la rioja",
  "America/Argentina/Mendoza": "argentina mendoza",
  "America/Argentina/Rio_Gallegos": "argentina rio gallegos",
  "America/Argentina/Salta": "argentina salta",
  "America/Argentina/San_Juan": "argentina san juan",
  "America/Argentina/San_Luis": "argentina san luis",
  "America/Argentina/Tucuman": "argentina tucuman",
  "America/Argentina/Ushuaia": "argentina ushuaia",
  "America/Aruba": "aruba",
  "America/Asuncion": "paraguay asuncion",
  "America/Atikokan": "canada atikokan",
  "America/Bahia": "brazil brasil bahia salvador",
  "America/Bahia_Banderas": "mexico bahia banderas",
  "America/Barbados": "barbados",
  "America/Belem": "brazil brasil belem",
  "America/Belize": "belize",
  "America/Blanc-Sablon": "canada blanc sablon",
  "America/Boa_Vista": "brazil brasil boa vista",
  "America/Bogota": "colombia bogota",
  "America/Boise": "usa united states idaho boise",
  "America/Cambridge_Bay": "canada cambridge bay nunavut",
  "America/Campo_Grande": "brazil brasil campo grande",
  "America/Cancun": "mexico cancun yucatan",
  "America/Caracas": "venezuela caracas",
  "America/Cayenne": "french guiana cayenne",
  "America/Cayman": "cayman islands",
  "America/Chicago": "usa united states illinois chicago central",
  "America/Chihuahua": "mexico chihuahua",
  "America/Ciudad_Juarez": "mexico ciudad juarez",
  "America/Coral_Harbour": "canada attawapiskat",
  "America/Costa_Rica": "costa rica san jose",
  "America/Coyhaique": "chile coyhaique",
  "America/Creston": "canada creston",
  "America/Cuiaba": "brazil brasil cuiaba",
  "America/Curacao": "curacao netherlands antilles",
  "America/Danmarkshavn": "greenland denmark danmarkshavn",
  "America/Dawson": "canada dawson yukon",
  "America/Dawson_Creek": "canada dawson creek bc",
  "America/Denver": "usa united states colorado denver mountain",
  "America/Detroit": "usa united states michigan detroit eastern",
  "America/Dominica": "dominica",
  "America/Edmonton": "canada alberta edmonton",
  "America/Eirunepe": "brazil brasil eirunepe",
  "America/El_Salvador": "el salvador san salvador",
  "America/Fort_Nelson": "canada fort nelson bc",
  "America/Fortaleza": "brazil brasil fortaleza",
  "America/Glace_Bay": "canada nova scotia glace bay",
  "America/Goose_Bay": "canada labrador goose bay",
  "America/Grand_Turk": "turks caicos grand turk",
  "America/Grenada": "grenada",
  "America/Guadeloupe": "guadeloupe france",
  "America/Guatemala": "guatemala guatemala city",
  "America/Guayaquil": "ecuador guayaquil quito",
  "America/Guyana": "guyana georgetown",
  "America/Halifax": "canada nova scotia halifax maritime",
  "America/Havana": "cuba havana",
  "America/Hermosillo": "mexico hermosillo sonora",
  "America/Indiana/Indianapolis": "usa united states indiana indianapolis eastern",
  "America/Indiana/Knox": "usa united states indiana knox central",
  "America/Indiana/Marengo": "usa united states indiana marengo",
  "America/Indiana/Petersburg": "usa united states indiana petersburg",
  "America/Indiana/Tell_City": "usa united states indiana tell city",
  "America/Indiana/Vevay": "usa united states indiana vevay",
  "America/Indiana/Vincennes": "usa united states indiana vincennes",
  "America/Indiana/Winamac": "usa united states indiana winamac",
  "America/Inuvik": "canada inuvik northwest territories",
  "America/Iqaluit": "canada iqaluit nunavut",
  "America/Jamaica": "jamaica kingston",
  "America/Juneau": "usa united states alaska juneau",
  "America/Kentucky/Louisville": "usa united states kentucky louisville eastern",
  "America/Kentucky/Monticello": "usa united states kentucky monticello eastern",
  "America/Kralendijk": "bonaire caribbean netherlands",
  "America/La_Paz": "bolivia la paz sucre",
  "America/Lima": "peru lima",
  "America/Los_Angeles": "usa united states california los angeles san francisco seattle pacific",
  "America/Lower_Princes": "sint maarten",
  "America/Maceio": "brazil brasil maceio",
  "America/Managua": "nicaragua managua",
  "America/Manaus": "brazil brasil manaus amazon",
  "America/Marigot": "saint martin",
  "America/Martinique": "martinique france",
  "America/Matamoros": "mexico matamoros",
  "America/Mazatlan": "mexico mazatlan sinaloa",
  "America/Menominee": "usa united states wisconsin menominee central",
  "America/Merida": "mexico merida yucatan",
  "America/Metlakatla": "usa united states alaska metlakatla",
  "America/Mexico_City": "mexico mexico city cdmx",
  "America/Miquelon": "saint pierre miquelon france",
  "America/Moncton": "canada new brunswick moncton",
  "America/Monterrey": "mexico monterrey",
  "America/Montevideo": "uruguay montevideo",
  "America/Montserrat": "montserrat",
  "America/Nassau": "bahamas nassau",
  "America/New_York": "usa united states new york boston washington miami eastern est",
  "America/Nome": "usa united states alaska nome",
  "America/Noronha": "brazil brasil fernando de noronha",
  "America/Nuuk": "greenland denmark nuuk godthab",
  "America/Ojinaga": "mexico ojinaga",
  "America/Panama": "panama panama city",
  "America/Paramaribo": "suriname paramaribo",
  "America/Phoenix": "usa united states arizona phoenix tucson mountain",
  "America/Port-au-Prince": "haiti port au prince",
  "America/Port_of_Spain": "trinidad tobago port of spain",
  "America/Porto_Velho": "brazil brasil porto velho",
  "America/Puerto_Rico": "puerto rico san juan",
  "America/Punta_Arenas": "chile punta arenas patagonia",
  "America/Rankin_Inlet": "canada rankin inlet nunavut",
  "America/Recife": "brazil brasil recife",
  "America/Regina": "canada saskatchewan regina",
  "America/Resolute": "canada resolute nunavut",
  "America/Rio_Branco": "brazil brasil rio branco acre",
  "America/Santarem": "brazil brasil santarem",
  "America/Santiago": "chile santiago",
  "America/Santo_Domingo": "dominican republic santo domingo",
  "America/Sao_Paulo": "brazil brasil sao paulo rio brt",
  "America/Scoresbysund": "greenland denmark scoresbysund ittoqqortoormiit",
  "America/Sitka": "usa united states alaska sitka",
  "America/St_Barthelemy": "saint barthelemy",
  "America/St_Johns": "canada newfoundland st johns",
  "America/St_Kitts": "saint kitts nevis",
  "America/St_Lucia": "saint lucia",
  "America/St_Thomas": "us virgin islands st thomas",
  "America/St_Vincent": "saint vincent grenadines",
  "America/Swift_Current": "canada saskatchewan swift current",
  "America/Tegucigalpa": "honduras tegucigalpa",
  "America/Thule": "greenland denmark thule pituffik",
  "America/Thunder_Bay": "canada ontario thunder bay",
  "America/Tijuana": "mexico tijuana baja",
  "America/Toronto": "canada ontario toronto ottawa montreal eastern",
  "America/Tortola": "british virgin islands tortola",
  "America/Vancouver": "canada british columbia vancouver victoria",
  "America/Virgin": "us virgin islands",
  "America/Whitehorse": "canada yukon whitehorse",
  "America/Winnipeg": "canada manitoba winnipeg central",
  "America/Yakutat": "usa united states alaska yakutat",
  "America/Yellowknife": "canada northwest territories yellowknife",
  "Antarctica/Casey": "antarctica australia casey",
  "Antarctica/Davis": "antarctica australia davis",
  "Antarctica/DumontDUrville": "antarctica france dumont d'urville",
  "Antarctica/Mawson": "antarctica australia mawson",
  "Antarctica/McMurdo": "antarctica usa mcmurdo new zealand",
  "Antarctica/Palmer": "antarctica chile palmer",
  "Antarctica/Rothera": "antarctica uk rothera",
  "Antarctica/Syowa": "antarctica japan syowa",
  "Antarctica/Troll": "antarctica norway troll",
  "Antarctica/Vostok": "antarctica russia vostok",
  "Arctic/Longyearbyen": "norway svalbard longyearbyen arctic",
  "Asia/Aden": "yemen aden",
  "Asia/Almaty": "kazakhstan almaty",
  "Asia/Amman": "jordan amman",
  "Asia/Anadyr": "russia anadyr chukotka",
  "Asia/Aqtau": "kazakhstan aqtau",
  "Asia/Aqtobe": "kazakhstan aqtobe",
  "Asia/Ashgabat": "turkmenistan ashgabat",
  "Asia/Atyrau": "kazakhstan atyrau",
  "Asia/Baghdad": "iraq baghdad",
  "Asia/Bahrain": "bahrain manama",
  "Asia/Baku": "azerbaijan baku",
  "Asia/Bangkok": "thailand bangkok vietnam cambodia indochina",
  "Asia/Barnaul": "russia barnaul altai",
  "Asia/Beirut": "lebanon beirut",
  "Asia/Bishkek": "kyrgyzstan bishkek",
  "Asia/Brunei": "brunei bandar seri begawan",
  "Asia/Chita": "russia chita zabaykalsky",
  "Asia/Choibalsan": "mongolia choibalsan",
  "Asia/Colombo": "sri lanka colombo",
  "Asia/Damascus": "syria damascus",
  "Asia/Dhaka": "bangladesh dhaka dacca",
  "Asia/Dili": "timor-leste east timor dili",
  "Asia/Dubai": "uae united arab emirates dubai abu dhabi gulf",
  "Asia/Dushanbe": "tajikistan dushanbe",
  "Asia/Famagusta": "cyprus famagusta",
  "Asia/Gaza": "palestine gaza strip",
  "Asia/Hebron": "palestine hebron west bank",
  "Asia/Ho_Chi_Minh": "vietnam ho chi minh saigon hanoi",
  "Asia/Hong_Kong": "hong kong china hksar",
  "Asia/Hovd": "mongolia hovd",
  "Asia/Irkutsk": "russia irkutsk siberia",
  "Asia/Jakarta": "indonesia jakarta java",
  "Asia/Jayapura": "indonesia jayapura papua",
  "Asia/Jerusalem": "israel jerusalem tel aviv",
  "Asia/Kabul": "afghanistan kabul",
  "Asia/Kamchatka": "russia kamchatka petropavlovsk",
  "Asia/Karachi": "pakistan karachi lahore islamabad",
  "Asia/Kathmandu": "nepal kathmandu ktm",
  "Asia/Khandyga": "russia khandyga yakutia",
  "Asia/Kolkata": "india kolkata calcutta mumbai delhi bangalore chennai ist",
  "Asia/Krasnoyarsk": "russia krasnoyarsk siberia",
  "Asia/Kuala_Lumpur": "malaysia kuala lumpur singapore penang",
  "Asia/Kuching": "malaysia kuching borneo",
  "Asia/Kuwait": "kuwait kuwait city",
  "Asia/Macau": "macau china macao",
  "Asia/Magadan": "russia magadan",
  "Asia/Makassar": "indonesia makassar sulawesi",
  "Asia/Manila": "philippines manila cebu",
  "Asia/Muscat": "oman muscat",
  "Asia/Nicosia": "cyprus nicosia",
  "Asia/Novokuznetsk": "russia novokuznetsk",
  "Asia/Novosibirsk": "russia novosibirsk siberia",
  "Asia/Omsk": "russia omsk",
  "Asia/Oral": "kazakhstan oral",
  "Asia/Phnom_Penh": "cambodia phnom penh",
  "Asia/Pontianak": "indonesia pontianak kalimantan",
  "Asia/Pyongyang": "north korea pyongyang dprk",
  "Asia/Qatar": "qatar doha",
  "Asia/Qostanay": "kazakhstan qostanay",
  "Asia/Qyzylorda": "kazakhstan qyzylorda",
  "Asia/Riyadh": "saudi arabia riyadh jeddah",
  "Asia/Sakhalin": "russia sakhalin yuzhno-sakhalinsk",
  "Asia/Samarkand": "uzbekistan samarkand tashkent",
  "Asia/Seoul": "south korea seoul korea busan kst",
  "Asia/Shanghai": "china shanghai beijing guangzhou cst prc",
  "Asia/Singapore": "singapore sgt",
  "Asia/Srednekolymsk": "russia srednekolymsk",
  "Asia/Taipei": "taiwan taipei taichung",
  "Asia/Tashkent": "uzbekistan tashkent",
  "Asia/Tbilisi": "georgia tbilisi",
  "Asia/Tehran": "iran tehran persian",
  "Asia/Thimphu": "bhutan thimphu",
  "Asia/Tokyo": "japan tokyo osaka kyoto jst nippon",
  "Asia/Tomsk": "russia tomsk",
  "Asia/Ulaanbaatar": "mongolia ulaanbaatar ulan bator",
  "Asia/Urumqi": "china urumqi xinjiang",
  "Asia/Ust-Nera": "russia ust-nera",
  "Asia/Vientiane": "laos vientiane",
  "Asia/Vladivostok": "russia vladivostok primorsky",
  "Asia/Yakutsk": "russia yakutsk",
  "Asia/Yangon": "myanmar burma yangon rangoon",
  "Asia/Yekaterinburg": "russia yekaterinburg ural",
  "Asia/Yerevan": "armenia yerevan",
  "Atlantic/Azores": "portugal azores",
  "Atlantic/Bermuda": "bermuda uk",
  "Atlantic/Canary": "spain canary islands las palmas",
  "Atlantic/Cape_Verde": "cape verde praia",
  "Atlantic/Faroe": "faroe islands denmark torshavn",
  "Atlantic/Madeira": "portugal madeira funchal",
  "Atlantic/Reykjavik": "iceland reykjavik",
  "Atlantic/South_Georgia": "south georgia sandwich uk",
  "Atlantic/Stanley": "falkland islands stanley",
  "Atlantic/St_Helena": "saint helena",
  "Australia/Adelaide": "australia adelaide south australia",
  "Australia/Brisbane": "australia brisbane queensland",
  "Australia/Broken_Hill": "australia broken hill nsw",
  "Australia/Darwin": "australia darwin northern territory",
  "Australia/Eucla": "australia eucla western australia",
  "Australia/Hobart": "australia hobart tasmania",
  "Australia/Lindeman": "australia lindeman queensland",
  "Australia/Lord_Howe": "australia lord howe island",
  "Australia/Melbourne": "australia melbourne victoria sydney",
  "Australia/Perth": "australia perth western australia",
  "Australia/Sydney": "australia sydney nsw canberra",
  "CET": "europe central cet",
  "CST6CDT": "usa central",
  "EET": "europe eastern eet",
  "EST": "usa eastern est",
  "EST5EDT": "usa eastern",
  "Etc/GMT": "utc gmt greenwich zulu",
  "Etc/GMT+1": "utc gmt minus 1",
  "Etc/GMT-1": "utc gmt plus 1",
  "Etc/UTC": "utc coordinated universal gmt zulu",
  "Europe/Amsterdam": "netherlands holland dutch amsterdam rotterdam",
  "Europe/Andorra": "andorra",
  "Europe/Astrakhan": "russia astrakhan",
  "Europe/Athens": "greece athens",
  "Europe/Belgrade": "serbia belgrade yugoslavia",
  "Europe/Berlin": "germany deutschland german berlin munich frankfurt hamburg",
  "Europe/Bratislava": "slovakia bratislava",
  "Europe/Brussels": "belgium brussels bruxelles",
  "Europe/Bucharest": "romania bucharest",
  "Europe/Budapest": "hungary budapest",
  "Europe/Busingen": "germany busingen",
  "Europe/Chisinau": "moldova chisinau",
  "Europe/Copenhagen": "denmark copenhagen",
  "Europe/Dublin": "ireland dublin eire",
  "Europe/Gibraltar": "gibraltar uk",
  "Europe/Guernsey": "guernsey channel islands uk",
  "Europe/Helsinki": "finland helsinki",
  "Europe/Isle_of_Man": "isle of man uk",
  "Europe/Istanbul": "turkey turkiye istanbul ankara",
  "Europe/Jersey": "jersey channel islands uk",
  "Europe/Kaliningrad": "russia kaliningrad",
  "Europe/Kirov": "russia kirov",
  "Europe/Kyiv": "ukraine kyiv kiev",
  "Europe/Lisbon": "portugal lisbon",
  "Europe/Ljubljana": "slovenia ljubljana",
  "Europe/London": "united kingdom uk britain england london scotland wales great britain gmt bst",
  "Europe/Luxembourg": "luxembourg",
  "Europe/Madrid": "spain madrid barcelona",
  "Europe/Malta": "malta valletta",
  "Europe/Mariehamn": "aland islands finland mariehamn",
  "Europe/Minsk": "belarus minsk",
  "Europe/Monaco": "monaco",
  "Europe/Moscow": "russia moscow saint petersburg msk",
  "Europe/Oslo": "norway oslo",
  "Europe/Paris": "france french paris lyon marseille",
  "Europe/Podgorica": "montenegro podgorica",
  "Europe/Prague": "czech republic czechia prague",
  "Europe/Riga": "latvia riga",
  "Europe/Rome": "italy italian rome milan",
  "Europe/Samara": "russia samara",
  "Europe/San_Marino": "san marino",
  "Europe/Sarajevo": "bosnia sarajevo",
  "Europe/Saratov": "russia saratov",
  "Europe/Simferopol": "ukraine crimea simferopol russia",
  "Europe/Skopje": "north macedonia skopje macedonia",
  "Europe/Sofia": "bulgaria sofia",
  "Europe/Stockholm": "sweden stockholm",
  "Europe/Tallinn": "estonia tallinn",
  "Europe/Tirane": "albania tirana tirane",
  "Europe/Ulyanovsk": "russia ulyanovsk",
  "Europe/Vaduz": "liechtenstein vaduz",
  "Europe/Vatican": "vatican holy see rome",
  "Europe/Vienna": "austria vienna",
  "Europe/Vilnius": "lithuania vilnius",
  "Europe/Volgograd": "russia volgograd",
  "Europe/Warsaw": "poland warsaw krakow",
  "Europe/Zagreb": "croatia zagreb",
  "Europe/Zurich": "switzerland swiss zurich geneva bern",
  "HST": "usa hawaii hst",
  "Indian/Antananarivo": "madagascar antananarivo",
  "Indian/Chagos": "british indian ocean territory chagos",
  "Indian/Christmas": "christmas island australia",
  "Indian/Cocos": "cocos islands australia",
  "Indian/Comoro": "comoros moroni",
  "Indian/Kerguelen": "french southern territories kerguelen",
  "Indian/Mahe": "seychelles mahe",
  "Indian/Maldives": "maldives male",
  "Indian/Mauritius": "mauritius port louis",
  "Indian/Mayotte": "mayotte france",
  "Indian/Reunion": "reunion france",
  "MET": "europe middle east",
  "MST": "usa mountain mst",
  "MST7MDT": "usa mountain",
  "Pacific/Apia": "samoa apia",
  "Pacific/Auckland": "new zealand nz auckland wellington",
  "Pacific/Bougainville": "papua new guinea bougainville",
  "Pacific/Chatham": "new zealand chatham islands",
  "Pacific/Chuuk": "micronesia chuuk",
  "Pacific/Easter": "chile easter island rapa nui",
  "Pacific/Efate": "vanuatu efate",
  "Pacific/Fakaofo": "tokelau fakaofo",
  "Pacific/Fiji": "fiji suva",
  "Pacific/Funafuti": "tuvalu funafuti",
  "Pacific/Galapagos": "ecuador galapagos",
  "Pacific/Gambier": "french polynesia gambier",
  "Pacific/Guadalcanal": "solomon islands guadalcanal honiara",
  "Pacific/Guam": "guam usa mariana",
  "Pacific/Honolulu": "usa hawaii honolulu oahu",
  "Pacific/Kanton": "kiribati kanton phoenix islands",
  "Pacific/Kiritimati": "kiribati kiritimati christmas island line",
  "Pacific/Kosrae": "micronesia kosrae",
  "Pacific/Kwajalein": "marshall islands kwajalein",
  "Pacific/Majuro": "marshall islands majuro",
  "Pacific/Marquesas": "french polynesia marquesas",
  "Pacific/Midway": "usa midway island",
  "Pacific/Nauru": "nauru",
  "Pacific/Niue": "niue",
  "Pacific/Norfolk": "norfolk island australia",
  "Pacific/Noumea": "new caledonia france noumea",
  "Pacific/Pago_Pago": "american samoa usa pago pago",
  "Pacific/Palau": "palau",
  "Pacific/Pitcairn": "pitcairn islands uk",
  "Pacific/Pohnpei": "micronesia pohnpei ponape",
  "Pacific/Port_Moresby": "papua new guinea port moresby",
  "Pacific/Rarotonga": "cook islands rarotonga",
  "Pacific/Saipan": "northern mariana saipan",
  "Pacific/Tahiti": "french polynesia tahiti papeete",
  "Pacific/Tarawa": "kiribati tarawa",
  "Pacific/Tongatapu": "tonga tongatapu nuku'alofa",
  "Pacific/Wake": "usa wake island",
  "Pacific/Wallis": "wallis futuna france",
  "PST8PDT": "usa pacific pst",
  "WET": "europe western wet"
};

/** IANA segments → searchable words (capitals in path, regions). */
function pathSegmentTerms(iana) {
  if (!iana || iana.startsWith("Etc/GMT") || iana === "Etc/UTC" || iana === "Etc/Zulu") {
    return "";
  }
  return iana
    .split("/")
    .map((seg) => seg.replace(/_/g, " ").toLowerCase())
    .filter((seg) => seg.length > 1)
    .join(" ");
}

/**
 * Country, capital, and regional keywords for calendar timezone search.
 * @param {string} iana
 * @returns {string} space-separated lowercase terms
 */
export function getRegionalSearchTerms(iana) {
  if (!iana) return "";
  const parts = [pathSegmentTerms(iana)];
  const exact = IANA_COUNTRY_CAPITAL[iana];
  if (exact) parts.push(exact);

  if (iana.startsWith("America/Argentina/")) {
    parts.push("argentina argentine");
  }

  if (iana.startsWith("America/") && !exact) {
    parts.push("usa united states america us");
  }

  return parts.filter(Boolean).join(" ");
}
